// Generated by https://quicktype.io

export interface StoreMachineResponse {
    message: string;
    data:    Data;
}

export interface Data {
    id:         string;
    id_machine: string;
    no:         string;
    updated_at: Date;
    created_at: Date;
    deletedAt:  null;
}
